### PR TITLE
Js of ocaml

### PR DESCRIPTION
**Pull request by gasche**
I saw in the [blog post](http://lambdamaphone.blogspot.fr/2015/12/generativity-interpretation-study-of.html) that you were interested in a JS port of the codebase, to render generated comics in a browser. I tried to use [js_of_ocaml](http://ocsigen.org/js_of_ocaml/) for that purpose, a compiler from OCaml to javascript.

The first commit just copies gen.sml unchanged (so that I can `git show --patience` the diff commit and look at the SML->OCaml changes), the second commit ports the code to OCaml, which is rather straightforward, and the third sets up a simplistic javascript compilation pipeline and a toy webpage to test it -- the OCaml-to-JS bridge in `html/bind_gen.ml` defines a function that takes `nves, min, max` in input and returns the JSON marshalling of the returned comic (as a string), so it should be very simple to develop pure-javascript display logic from that.

(It is also possible to write the rendering logic on the OCaml side as the js_of_ocaml project provides libraries to generate HTML, access the DOM and call arbitrary javascript libraries.)

### CODE REVIEW

**Comment by gasche** [comment]
To give an idea of the resulting HTML interaction, I uploaded a [working demo](http://gallium.inria.fr/~scherer/tmp/comicgen/) in a temporary location -- I plan to remove it once I get feedback on the pull request.

**Comment by chrisamaphone** [comment]
Awesome! Thank you so much for figuring out this glue code and for the pointer to the js_of_ocaml project!

**Comment by chrisamaphone** [comment]
Hi there. I'm returning to this project again, and I am having trouble building the code you checked in; could you help me with it? I've installed js_of_ocaml through OPAM, but it doesn't seem to be recognized by ocamlbuild. Specifically, the error I get is:

ocamlfind: Package `js_of_ocaml.ocamlbuild' not found

Running "ocamlfind query js_of_ocaml" succeeds; I'm not sure what the ".ocamlbuild" syntax refers to or which parts are not connected properly.

**Comment by gasche** [comment]
My pleasure.

`js_of_ocaml.ocamlbuild` the name of an ocamlfind sub-package (a package inside the "js_of_ocaml" package) that provides an ocamlbuild plugin that contains the logic for easily building `.js` files from OCaml sources using `js_of_ocaml`.

Which versions of OCaml and js_of_ocaml have you installed? I am using js_of_ocaml 2.7, and it does come with the ocamlbuild plugin. From what I can tell, the js_of_ocaml people wrote this plugin in September 2013, so it should be part of all 2.x releases.

**Comment by gasche** [comment]
P.S.: to know which js_of_ocaml.foo packages are installed on a given opam switch, I use

```
$ ocamlfind list | grep js_of_ocaml
js_of_ocaml         (version: 2.7)
js_of_ocaml.compiler (version: [distributed with js_of_ocaml])
js_of_ocaml.compiler.with_findlib (version: n/a)
js_of_ocaml.graphics (version: [distributed with js_of_ocaml])
js_of_ocaml.log     (version: [distributed with js_of_ocaml])
js_of_ocaml.ocamlbuild (version: [distributed with js_of_ocaml])
js_of_ocaml.ppx     (version: [distributed with js_of_ocaml])
js_of_ocaml.ppx.internal (version: [distributed with js_of_ocaml])
js_of_ocaml.syntax  (version: [distributed with js_of_ocaml])
js_of_ocaml.toplevel (version: [distributed with js_of_ocaml])
js_of_ocaml.weak    (version: [distributed with js_of_ocaml])
```

**Comment by chrisamaphone** [comment]
The version was in fact the problem! Once I updated opam and convinced it
to install a newer js_of_ocaml, building works. Thanks!

**Pull request merged**
